### ISSUE TITLE
Error running stored procedure

### ISSUE THREAD

**Issue by Pramishka** [crimdon/SQLToolkit#1]
Installed this SQL Toolkit extension on our TFS Server/collection and used the SQL Toolkit task Run Stored Procedure. I am not using sql server login ID rather letting it default to the build agent user which has the required permissions. However the task fails: Error running stored procedure - no other exceptions. Question does one have to use SQL Server Login? If not what else could be the issue - the server instance, database, stored procedure all appears to be fine.......

**Comment by crimdon** [comment]
You don't have to use a SQL Login. I use a domain account that runs the build agent and it has rights to the SQL server running the stored procedure. This all runs OK in my environment.

Have you tried logging on using the domain account running the build agent and manually running the stored procedure using SSMS?

**Comment by Pramishka** [comment]
The domain account that runs the build agent needed the ability to log on locally on the build server besides the permissions on the SQL Server to run the SP. Thanks for the suggestions......
