### ISSUE TITLE
Error handling BROKEN

### ISSUE THREAD

**Issue by sevaa** [crimdon/SQLToolkit#11]
In update 1.7.13, SQL errors don't register as errors in TFS RMI. As a result, a task might fail, but the rest of the release definition will continue executing. This is unacceptable; the decision to ignore errors or fail the whole release should be driven by the "Continue on error" checkbox in the task properties.

Use Write-Error instead of Write-Host in the catch handler.

**Comment by crimdon** [comment]
Fixed
