### ISSUE TITLE
Cannot bind argument to parameter 'command' because it is an empty string.

### ISSUE THREAD

**Issue by CowboyPurest** [crimdon/SQLToolkit#13]
I am getting this error when trying to use this package "Cannot bind argument to parameter 'command' because it is an empty string." all of the parameters are filled

**Comment by crimdon** [comment]
Can you tell me which task you are using please?

**Comment by CowboyPurest** [comment]
I am trying to use RunSQLCommand

**Comment by CowboyPurest** [comment]
just let me know what information you need and I will get it to you

**Comment by crimdon** [comment]
I've tried and failed to replicate this issue. Can you tell me what sort of SQL command you are trying to run? I've tried tried running multi line selects/updates and stored procs without any issue.

**Comment by CowboyPurest** [comment]
"ALTER DATABASE $(SourceDatabase) SET SINGLE_USER WITH ROLLBACK IMMEDIATE"

I have taken your powershell script out of github modified it to take parameters instead of using the vsbinding  and run it with the powershell tool and it has worked.

**Comment by crimdon** [comment]
I've tried your command, created a variable for my build and it worked OK. Even setting the variable value to empty does not give the same error message.

Have you tried creating a SQL script and using the Run Script task? I was wondering if you get the same error message. If you do, then its starting to look like an environment problem.
