### ISSUE TITLE
SQL Backup Type:  Copy-Only

### ISSUE THREAD

**Issue by plraustin** [crimdon/SQLToolkit#15]
Need option to backup database without affecting the differential base.

Example:  

BACKUP DATABASE Sales
TO DISK = 'E:\BAK\Sales_Copy.bak'
WITH COPY_ONLY;

https://msdn.microsoft.com/en-us/library/ms191495.aspx

**Comment by crimdon** [comment]
Added and will post new version sometime today

**Comment by crimdon** [comment]
New version tested and uploaded to marketplace
