### ISSUE TITLE
How to log the errors for RunSqlScripts task?

### ISSUE THREAD

**Issue by dipenpatelOEH** [crimdon/SQLToolkit#17]

**Comment by crimdon** [comment]
It appears the Invoke-sqlcmd has a bug in it

https://connect.microsoft.com/SQLServer/feedback/details/779320/invoke-sqlcmd-does-not-return-t-sql-errors.

From what I've read on Stackoverflow, the bug has been fixed in SQL 2014 (I'm guessing this has to be the powershell modules on your build server).

**Comment by crimdon** [comment]
All issues have new been fixed in new version

**Comment by dipenpatelOEH** [comment]
Hi Andrew,

Thanks for getting it fixed.

However the fix to drop the PowerShell SQLCMD increases issue for us.

The build service account would have ddl_admin, ddl_datawriter and ddl_datareader role membership and DBAs and Governance does not want the build account to modify the security/permissions of the database to be automated.

We are using SSDT for database development and using the SQLPackage.exe to generate to DeployReport and Scripts which DBAs will verify before they approve the deployment in UAT/PROD.

As you know the scripts generated by from dacpac by SSDT or SQLPackage.exe requires SQLCMD to be enabled.

We found your SQLToolkit to be perfect fit in the planned automation process, where it allowed the DBAs to review the Deploy report and scripts before they approve deployment except error logging within TFS.

If you can please re-enable(or have the different task for) the PowerShell  version, that would be great. I will find a workaround to see the errors if error logging cannot be fixed with Powershell SQLCMD option.


Regards
Dipen





[cid:image002.jpg@01D29982.6325DE30]



[cid:image005.jpg@01D29982.6325DE30]



[cid:image009.jpg@01D29982.6325DE30]




[cid:image012.jpg@01D29982.6325DE30]

**Comment by crimdon** [comment]
Hi Dipen,


It looks handler I added to get some advanced logging from the DACPAC needed higher permissions. I'll try and pin that down more but until then, I've re-released the the toolkit and made the advanced logging optional on the DACPAC task.


Regards,


Andrew Lackenby

________________________________

**Comment by crimdon** [comment]
Hi Dipen,


Just managed to do a bit more testing and the minimum per permissions I needed to give myself (for quite a simple package) was db_ddladmin and db_securityadmin. Anything else produced a permissions error when applying the DACPAC.


Regards,


Andrew Lackenby

________________________________
