### ISSUE TITLE
SQL Skripts with GO Statements

### ISSUE THREAD

**Issue by swtrse** [crimdon/SQLToolkit#18]
For test purposes I took your single sql powershell script and make a few changes. Know it works for scripts with GO like a charm.
The perfect way since the Batchstatement is configurable would be a parameter with default value [gG][oO] that is tested in the Split statement
`
    #Execute the query
    $scriptContent = Get-Content $sqlScript | Out-String
    $batches = $scriptContent -split "\s*GO\s*\r?\n"

    foreach($batch in $batches)
    {
        if($batch.Trim() -ne "")
        {
            $SqlCmd.CommandText = $batch
	        $SqlCmd.ExecuteNonQuery()
        }
    }

    $SqlConnection.Close()
`

**Comment by swtrse** [comment]
I just created my test skript that works like a charm.
Only thing missing that I want to add is the possibility to set 
QUOTED_IDENTIFIER
ANSI_NULL_DFLT_ON
IMPLICIT_TRANSACTIONS
CURSOR_CLOSE_ON_COMMIT
ANSI_PADDING
ANSI_WARNINGS
ANSI_NULLS
if necesary

`#DBSkript 
Param
(
    [string]$sqlScript,
    [string]$serverName,
    [string]$databaseName,
    [string]$userName = $null,
    [string]$userPassword = $null,
    [string]$queryTimeout = "30",
    [string]$batchDelimiter = "[gG][oO]"
)
Try
{
    $SqlConnection = New-Object System.Data.SqlClient.SqlConnection
    	
	if([string]::IsNullOrEmpty($userName))
    {
        $SqlConnection.ConnectionString = "Server=$serverName;Initial Catalog=$databaseName;Trusted_Connection=True;Connection Timeout=30;"		
    }
    else {
        $SqlConnection.ConnectionString = "Server=$serverName;Initial Catalog=$databaseName;User ID=$userName;Password=$userPassword;Connection Timeout=30;"
    }

    $handler = [System.Data.SqlClient.SqlInfoMessageEventHandler] {param($sender, $event) Write-Host $event.Message -ForegroundColor DarkBlue} 
    $SqlConnection.add_InfoMessage($handler) 
	$SqlConnection.Open()
	$SqlCmd = New-Object System.Data.SqlClient.SqlCommand
	$SqlCmd.Connection = $SqlConnection
	$SqlCmd.CommandTimeout = $queryTimeout

    Write-Host "Running Script " $sqlScript " on Database " $databaseName
		
    #Execute the query
    $scriptContent = Get-Content $sqlScript | Out-String
    $batches = $scriptContent -split "\s*$batchDelimiter\s*\r?\n"

    foreach($batch in $batches)
    {
        if($batch.Trim() -ne "")
        {
            $SqlCmd.CommandText = $batch
	        $reader = $SqlCmd.ExecuteNonQuery()
        }
    }

    $SqlConnection.Close()
    Write-Host "Finished"
}

Catch {
	Write-Host "Error running SQL script: $_" -ForegroundColor Red
	throw $_
}

`

**Comment by crimdon** [comment]
I've added this to the RunSingleSqlScript and RunSqlScripts tasks and release a new version

**Comment by sumo300** [comment]
> I've added this to the RunSingleSqlScript and RunSqlScripts tasks and release a new version

I grabbed latest and while it solved an issue with the `RunSingleSqlScript` task, I still get errors with GO statements when using the `RunSqlScripts` task.  

`[error]Exception calling "ExecuteNonQuery" with "0" argument(s): "Incorrect syntax near 'GO'."`

All of this was working fine 2 releases ago.

UPDATE: According to the release logs, it is still trying to run 2.1.0 version of the task.  Uninstall/reinstall of what is versioned as 2.2 is still running tasks with version 2.1.

```
2017-03-18T17:58:34.3388661Z ##[section]Starting: Run Sql Scripts on ***
2017-03-18T17:58:34.3544879Z ==============================================================================
2017-03-18T17:58:34.3544879Z Task         : Run Sql Scripts
2017-03-18T17:58:34.3544879Z Description  : Allows you to run SQL Scripts
2017-03-18T17:58:34.3544879Z Version      : 2.1.0
2017-03-18T17:58:34.3544879Z Author       : Andrew Lackenby
2017-03-18T17:58:34.3544879Z Help         : 
2017-03-18T17:58:34.3544879Z ==============================================================================
```

**Comment by crimdon** [comment]
I've had this issue before. Sometimes I've had to edit the task in order for it to download the latest version of the task script. If you go to the folder where the build agent is, you can delete all of the tasks from there and it downloads them again from TFS
