### ISSUE TITLE
Add the Option to change Settings into the task

### ISSUE THREAD

**Issue by swtrse** [crimdon/SQLToolkit#19]
It would be great if there woult be the option to set some settings with the task,

I extendet my script so that i is possible
The script reads the settings set on the database level and uses these settings for the SQL session.
So far this is the only way I found to consider the database settings and run scripts based on that settings instead of the session defaults.

I also added the param msSqlManagementStudioDefaultSets to quickly set the default settings of the Microsoft Sql Management Studio.

`#DBSkript 
Param
(
    [string]$sqlScript,
    [string]$serverName,
    [string]$databaseName,
    [string]$userName = $null,
    [string]$userPassword = $null,
    [string]$queryTimeout = "60",
    [string]$batchDelimiter = "[gG][oO]",
    [boolean]$msSqlManagementStudioDefaultSets = $false,
    [Nullable[boolean]]$ansiNullDefaultOn = $null,
    [Nullable[boolean]]$ansiNulls = $null,
    [Nullable[boolean]]$ansiPadding = $null,
    [Nullable[boolean]]$ansiWarnings = $null,
    [Nullable[boolean]]$arithabort = $null,
    [Nullable[boolean]]$concatNullYieldsNull = $null,
    [Nullable[boolean]]$numericRoundabort = $null,
    [Nullable[boolean]]$quotedIdentifier = $null,
    [Nullable[boolean]]$CursorCloseOnCommit = $null
)

Function IIf($If, $Right, $Wrong)
{
    If ($If) 
    {
        $Right
    } 
    Else 
    {
        $Wrong
    }
}

Try
{
    $SqlConnection = New-Object System.Data.SqlClient.SqlConnection
    	
	if([string]::IsNullOrEmpty($userName))
    {
        $SqlConnection.ConnectionString = "Server=$serverName;Initial Catalog=$databaseName;Trusted_Connection=True;Connection Timeout=30;"		
    }
    else {
        $SqlConnection.ConnectionString = "Server=$serverName;Initial Catalog=$databaseName;User ID=$userName;Password=$userPassword;Connection Timeout=30;"
    }

    $handler = [System.Data.SqlClient.SqlInfoMessageEventHandler] {param($sender, $event) Write-Host $event.Message -ForegroundColor DarkBlue} 
    $SqlConnection.add_InfoMessage($handler) 
	$SqlConnection.Open()
	$SqlCmd = New-Object System.Data.SqlClient.SqlCommand
	$SqlCmd.Connection = $SqlConnection
	$SqlCmd.CommandTimeout = $queryTimeout

    If ($msSqlManagementStudioDefaultSets -eq $true)
    {
        $ansiNulls = $true
        $ansiPadding = $true
        $ansiWarnings = $true
        $arithabort = $true
        $concatNullYieldsNull = $true
        $numericRoundabort = $null
        $quotedIdentifier = $true
        $CursorCloseOnCommit = $false
    }

    Write-Host "Running Script " $sqlScript " on Database " $databaseName
	$SqlCmd.CommandText = "SELECT SUM(h.Val)
                                FROM 
                                (
                                	SELECT CAST(DATABASEPROPERTYEX('$databaseName' , 'IsAnsiNullDefault') AS int) * 1024 Val
                                	UNION ALL
                                	SELECT CAST(DATABASEPROPERTYEX('$databaseName' , 'IsAnsiNullsEnabled') AS int) * 32 Val
                                	UNION ALL
                                	SELECT CAST(DATABASEPROPERTYEX('$databaseName' , 'IsAnsiPaddingEnabled') AS int) * 16 Val
                                	UNION ALL
                                	SELECT CAST(DATABASEPROPERTYEX('$databaseName' , 'IsAnsiWarningsEnabled') AS int) * 8 Val
                                	UNION ALL
                                	SELECT CAST(DATABASEPROPERTYEX('$databaseName' , 'IsArithmeticAbortEnabled') AS int) * 64 Val
                                	UNION ALL
                                	SELECT CAST(DATABASEPROPERTYEX('$databaseName' , 'IsNullConcat') AS int) * 4096 Val
                                	UNION ALL
                                	SELECT CAST(DATABASEPROPERTYEX('$databaseName' , 'IsNumericRoundAbortEnabled') AS int) * 8192 Val
                                	UNION ALL
                                	SELECT CAST(DATABASEPROPERTYEX('$databaseName' , 'IsQuotedIdentifiersEnabled') AS int) * 256 Val
                                	UNION ALL
                                	SELECT CAST(DATABASEPROPERTYEX('$databaseName' , 'IsCloseCursorsOnCommitEnabled') AS int) * 4 Val
                                ) h;"
    [int] $sqlSettings = [int]$SqlCmd.ExecuteScalar();
    If ($ansiNullDefaultOn -eq $null) { $ansiNullDefaultOn = ($sqlSettings -shr 10) % 2 -eq 1 }
    If ($ansiNulls -eq $null) { $ansiNulls = ($sqlSettings -shr 5) % 2 -eq 1 }
    If ($ansiPadding -eq $null) { $ansiPadding = ($sqlSettings -shr 4) % 2 -eq 1 }
    If ($ansiWarnings -eq $null) { $ansiWarnings = ($sqlSettings -shr 3) % 2 -eq 1 }
    If ($arithabort  -eq $null) { $arithabort = ($sqlSettings -shr 6) % 2 -eq 1 }
    If ($concatNullYieldsNull -eq $null) { $concatNullYieldsNull = ($sqlSettings -shr 12) % 2 -eq 1 }
    If ($numericRoundabort -eq $null) { $numericRoundabort = ($sqlSettings -shr 13) % 2 -eq 1 }
    If ($quotedIdentifier-eq $null) { $quotedIdentifier = ($sqlSettings -shr 8) % 2 -eq 1 }
    If ($CursorCloseOnCommit -eq $null) { $CursorCloseOnCommit = ($sqlSettings -shr 2) % 2 -eq 1 }

    [string]$settingsString = "";
    [string]$currentSet;
    Write-Host "Running with SQL Settings"
    $currentSet = "SET ANSI_NULL_DFLT_ON " + (IIf ($ansiNullDefaultOn -eq $true) "ON" "OFF") + ";"
    $settingsString = $settingsString + $currentSet + " "
    Write-Host $currentSet
    $currentSet = "SET ANSI_NULLS " + (IIf ($ansiNulls -eq $true) "ON" "OFF") + ";"
    $settingsString = $settingsString + $currentSet + " "
    Write-Host $currentSet
    $currentSet = "SET ANSI_PADDING " + (IIf ($ansiPadding -eq $true) "ON" "OFF") + ";"
    $settingsString = $settingsString + $currentSet + " "
    Write-Host $currentSet
    $currentSet = "SET ANSI_WARNINGS " + (IIf ($ansiWarnings -eq $true) "ON" "OFF") + ";"
    $settingsString = $settingsString + $currentSet + " "
    Write-Host $currentSet
    $currentSet = "SET ARITHABORT " + (IIf ($arithabort -eq $true) "ON" "OFF") + ";"
    $settingsString = $settingsString + $currentSet + " "
    Write-Host $currentSet
    $currentSet = "SET CONCAT_NULL_YIELDS_NULL " + (IIf ($concatNullYieldsNull -eq $true) "ON" "OFF") + ";"
    $settingsString = $settingsString + $currentSet + " "
    Write-Host $currentSet
    $currentSet = "SET NUMERIC_ROUNDABORT " + (IIf ($numericRoundabort -eq $true) "ON" "OFF") + ";"
    $settingsString = $settingsString + $currentSet + " "
    Write-Host $currentSet
    $currentSet = "SET QUOTED_IDENTIFIER " + (IIf ($quotedIdentifier -eq $true) "ON" "OFF") + ";"
    $settingsString = $settingsString + $currentSet + " "
    Write-Host $currentSet
    $currentSet = "SET CURSOR_CLOSE_ON_COMMIT " + (IIf ($CursorCloseOnCommit -eq $true) "ON" "OFF") + ";"
    $settingsString = $settingsString + $currentSet
    Write-Host $currentSet

    $SqlCmd.CommandText = $settingsString
    $reader = $SqlCmd.ExecuteNonQuery()
    
    #Execute the query
    $scriptContent = Get-Content $sqlScript | Out-String
    $batches = $scriptContent -split "\s*$batchDelimiter\s*\r?\n"

    foreach($batch in $batches)
    {
        if($batch.Trim() -ne "")
        {
            $SqlCmd.CommandText = $batch
	        $reader = $SqlCmd.ExecuteNonQuery()
        }
    }

    $SqlConnection.Close()
    Write-Host "Finished"
}

Catch {
	Write-Host "Error running SQL script: $_" -ForegroundColor Red
	throw $_
}`

**Comment by swtrse** [comment]
For the Task you can Skip the [boolean]$msSqlManagementStudioDefaultSets = $false parameter and do that over the task gui. Where The Check Boxes for the Set gets automatically checked...

**Comment by crimdon** [comment]
Sorry but I don't have the spare time to look at this at the moment. I might get time to look at it in a few weeks time depending on my workload.

Feel free though to take a copy of the repo and create a pull request with the modified code.
