### ISSUE TITLE
Request: Add the ability to support wildcard in paths, such as RunDACPAC

### ISSUE THREAD

**Issue by shieldsjared** [crimdon/SQLToolkit#22]
It would be very helpful if RunDACPAC supported wildcards for paths.  We maintain our DACPAC's in nuget packages and do not want to have to statically set the path to the nuget package (which includes the version #).

Thanks!!

**Comment by crimdon** [comment]
I don't know how easy that would be to implement but I'll have a look. Maybe an existing copy task would work?

**Comment by shieldsjared** [comment]
I'm testing a couple things now. If we come up with an elegant solution, I'll submit a PR

**Comment by shieldsjared** [comment]
Copy files task did the trick!  Thanks for the idea!!
