### ISSUE TITLE
Getting errors executing task RunSQL scripts on database

### ISSUE THREAD

**Issue by greadtm** [crimdon/SQLToolkit#24]
Any ideas on how to correct this error?

2017-06-05T19:44:42.5412825Z Running Script  test.sql
2017-06-05T19:44:42.6194063Z Error running SQL script: Exception calling "ExecuteNonQuery" with "0" argument(s): "Incorrect syntax near ','."
2017-06-05T19:44:42.6194063Z ##[debug]Caught exception from task script.
2017-06-05T19:44:42.6194063Z ##[debug]Error record:
2017-06-05T19:44:42.6975371Z ##[debug]ForEach-Object : Exception calling "ExecuteNonQuery" with "0" argument(s): "Incorrect syntax near ','."
2017-06-05T19:44:42.6975371Z ##[debug]At D:\Agent_SmartCoDEV_V2\_tasks\RunSqlScripts_a614c885-96bc-42ed-9369-ea36103dd898\2.1.8\RunSqlScripts.ps1:44 char:9
2017-06-05T19:44:42.6975371Z ##[debug]+         ForEach-Object { $SqlCmd.CommandText = $_.Trim(); $reader = $SqlCmd.Exec ...
2017-06-05T19:44:42.6975371Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-06-05T19:44:42.6975371Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [ForEach-Object], MethodInvocationException
2017-06-05T19:44:42.6975371Z ##[debug]    + FullyQualifiedErrorId : SqlException,Microsoft.PowerShell.Commands.ForEachObjectCommand

**Comment by crimdon** [comment]
The powershell script splits the SQL up into chunks by using the GO statement as a seperator. Looking at the error, I was wondering if you have 2 GO statements together with nothing inbetween?

**Comment by greadtm** [comment]
Hi Andrew.

This doesn’t appear to be the case. I am able to execute the SQL successfully via SSMS on the same TFS VNext server executing the deployments. I tried moving the comment block to the top of the SQL but it didn’t help.

Any advice on where to look next?

Thanks.
Greg

**Comment by greadtm** [comment]
To answer your previous question, we do not have a GO statements with nothing in between. All sections of the SQL have blocks of SQL to be executed.

**Comment by crimdon** [comment]
OK I've seem this bug before but thought I'd fixed it. Can you confirm what version of the extension you are using and what version of the script is running? Also are you using it on TFS or VSTS?

**Comment by greadtm** [comment]
We have TFS 2017 update 2 installed on prem.
We started with version 2.2.1. We updated our TFS UAT environment to version 2.3.0 of the SQLToolKit.
We are still having the same error when deploying SQL that contains multiple GO separators with valid SQL in between each. Is there any other information you would like?

**Comment by crimdon** [comment]
I'm still stuck with TFS 2015 so hopefully it won't be the changes there. One bug I remember not being able to fix was if an inline comment (i.e. --) had the word go in it.

**Comment by crimdon** [comment]
Can you please make sure that the build agent is using 2.1.11 version of the task? Sometimes I've noticed that TFS doesn't not download the latest version to your build server.

**Comment by greadtm** [comment]
{
    "id": "a614c885-96bc-42ed-9369-ea36103dd898",
    "name": "RunSqlScripts",
    "friendlyName": "Run Sql Scripts",
    "description": "Allows you to run SQL Scripts",
    "author": "Andrew Lackenby",
    "category": "Utility",
    "version": {
        "Major": "2",
        "Minor": "1",
        "Patch": "8"
    },

Have you found of a reliable way to force an update?

**Comment by crimdon** [comment]
The only way or forcing it appears to be to browse to the folder where the agent tasks are downloaded and delete them. When the build agent next runs, it downloads them from the extension.

**Comment by greadtm** [comment]
I actually established a new agent on the server with no downloaded tasks. Despite the fact that we have version 2.3.0 of this add on installed, its still downloading version 2.1.8 of the task. Very strange...

**Comment by greadtm** [comment]
Task table entry in the DB:
DisplayName	MajorVersion	MinorVersion	PatchVersion	ContributionIdentifier	ContributionVersion
Run Single SQL Script	2	1	11	andrewlackenby.sql-toolkit.runsinglesqlscript	2.3.0

**Comment by crimdon** [comment]
Maybe try removing the task and re-adding it? This looks like a TFS bug

**Comment by greadtm** [comment]
RunSQLScript is version 2.1.11. RunSqlScripts is version 2.1.8. We have been using the latter.

**Comment by crimdon** [comment]
Ah right my mistake.

I can't replicate the error you're getting. I've seen it in the past but thought I'd eliminated it. The power shell script uses a REGEX expression to split the SQL script into batches if it uses GO command. I've tried adding comments using the word go and also adding variables with go in them but it always runs OK. Is there any chance you can post or email me a copy of your script?

**Comment by greadtm** [comment]
Did the fixes you made in RunSQLScript make it into RunSQLScripts?

**Comment by crimdon** [comment]
I'll check but I'm sure I used the same method in both

Edit yes the same method is used in both scripts:
` #Execute the query
    (Get-Content $sqlScript | Out-String) -split '(?s)/\*.*?\*/' -split '\r?\ngo\r?\n' -notmatch '^\s*$' |
        ForEach-Object { $SqlCmd.CommandText = $_.Trim(); $reader = $SqlCmd.ExecuteNonQuery() }`

**Comment by jabbera** [comment]
This appears to be an issue with the logic to remove comments. The following should return 1, but it's being piped in to be executed as 5 different commands:

    $text = "select	a,
	/*  1 */ b,
   	/*  2 */ c,
	/*  3 */ d,
	/*  4 */ e
    from A
    GO
    "

    ($text -split '(?s)/\*.*?\*/' -split '\r?\ngo\r?\n' -notmatch '^\s*$').Length

**Comment by jabbera** [comment]
See: https://github.com/crimdon/SQLToolkit/pull/25 

for a potential fix.

**Comment by crimdon** [comment]
Yes I think that could work. The only reason I introduced the removal of comments was because somebody had GO commands in a command block. Also had a request to make the removal of comments optional so will probable introduce a dropdown that will handle comments in different ways.

Would be lots easier if powershell handled GO commands

**Comment by crimdon** [comment]
I've created a new version that replaces comments with a space. Also you can leave the comments in as long as they do not contain the keyword GO
