### ISSUE TITLE
Support for multiple DB servers and multiple DBs

### ISSUE THREAD

**Issue by greadtm** [crimdon/SQLToolkit#28]
We are using the Execute SQL Scripts task.
Scenario 1: We have a team that deploys a set of SQL files to a single server but multiple databases. Does the task support comma separated database names?
Scenario 2: We have a team that deploys a set of SQL files to multiple DB servers. Does the task support a comma separated database server names?
We are really trying to avoid creating tons of tasks in the release definition to support the release.
Thanks.

**Comment by crimdon** [comment]
It won't support comma delimited lists for database names at the moment but could incorporate this into a future release if there is a requirement.

**Comment by greadtm** [comment]
We would appreciate you including this into a future requirement. We have a number of teams that have both multiple databases on a single server. We would also like to deploy across multiple servers with a single task. Thanks.

**Comment by crimdon** [comment]
Actually it proved to be easy so have released a new version 2.5.0 with availability to to comma separate lists of servers and databases. #30

**Comment by greadtm** [comment]
Thanks for the quick turnaround. We will test it out.
