### ISSUE TITLE
Just upgraded from 1.8 to 2.4.2 started getting an error Incorrect syntax near ':'

### ISSUE THREAD

**Issue by plraustin** [crimdon/SQLToolkit#29]

**Comment by plraustin** [comment]
This is when using Run single SQL Task.  How do I rollback to the previous version that was working for us?

**Comment by plraustin** [comment]
Does this still support SQLCMD-mode commands?

**Comment by crimdon** [comment]
I removed the Invoke-SqlCmd from version 2 and replaced it with dot net style SQL client so it won't support SQLCMD-mode commands. I did this for better error handling as Invoke-SqlCmd has bugs in it.

I'll get hold of version 1.8 for you and put it on here if you want to roll back.

**Comment by crimdon** [comment]
Version 1.8.1 is on here (under releases) if you want to download it and roll back
