### ISSUE TITLE
Incompatible with MSSQL 2008

### ISSUE THREAD

**Issue by sevaa** [crimdon/SQLToolkit#3]
MS SQL Server 2008 doesn't have the SQLPS PowerShell module. Instead, one needs to explicitly add two snap-ins to the PowerShell session in the beginning of the script:

```
Add-PSSnapin SqlServerCmdletSnapin100
Add-PSSnapin SqlServerProviderSnapin100
```

As a result, none of the SQLToolkit tasks work on a SQL 2008 server.

**Comment by crimdon** [comment]
Hi there,

I've not been able to test this but...
1. Log on to the server running your build agent as the domain account that runs that service.
2. Create a PowerShell profile that loads these modules on startup.

[Click here for example](http://www.sqlservercentral.com/articles/Stairway+Series/91442/)

**Comment by sevaa** [comment]
Or you can conditionally load the snapins if the required cmdlet is not available. I did just that, see pull request #4.

**Comment by crimdon** [comment]
Hi there,

I've uploaded that as a new version. Let me know if it works please

**Comment by sevaa** [comment]
Tested "Run a query" and "Run a single script" on a SQL 2008 R2 instance. Works as expected. Since the inserted snippet is identical in all files, didn't test the rest.

I've discovered a new bug, though - decent error diagnostics is lacking. A script tried to violate a unique constraint, it errored out, but there was no sensible error message release execution logs, as if the exception object is not populated. I'll investigate further, then file a bug.

**Comment by sevaa** [comment]
Did you upload it to the VS gallery? Which is the new version? I still see the old script executing on my servers. How can one refresh gallery extensions in TFS RM, please?

**Comment by crimdon** [comment]
Yes I uploaded the new version this afternoon. After downloading the new version, you need to go to the collection admin page on your TFS server and then the extension tab. You can select and upload local extensions from there.

**Comment by sevaa** [comment]
Hm, I've deleted the extension from my team collection, then added (from local, not from gallery) again - the version of the script file on the server didn't change. I even deleted it from the working folder on the server, then rerun the release - it's still the version of the script that came with 1.6.0. Even the folder name is 1.6.0. Maybe you need to bump the version number not just on the extension, but on all scripts too.

**Comment by crimdon** [comment]
Did you update the extension to the latest version?

**Comment by crimdon** [comment]
I'll increase the version number and release

**Comment by sevaa** [comment]
> Did you update the extension to the latest version?

How and where? On collection level, I clicked "Uninstall", then Find extensions/Local, found SQL Toolkit (version 1.7.0), and so forth.

Looks like TFS maintains a local cache of gallery extensions that needs to be refreshed somehow. I could not find the means to do so in server-level admin settings.

EDIT: nevermind, figured it out. Needed to click "Update" in the local extension gallery. It's at 1.7.10 now. I still have to check if TFS RM redownloads a task script to a target server if the task version didn't change.
