### ISSUE TITLE
Setting Params for the Run Stored Procedure task

### ISSUE THREAD

**Issue by ptrubs** [crimdon/SQLToolkit#31]
Yo,

I would like to know how to set parameters for the Run Stored Procedure task?   Your screenshot for that task does not have an example in the field.  (Can you add an example of how to set params to the image pls?)

(actually I found it by reading the Powershell, so all good here - but It would have saved me a few minutes to have a better example)

awesome tool btw!

**Comment by crimdon** [comment]
The parameters are just passed in with a string so you can populate the field like:

@param1 = 1, @param2 = 'test'
