### ISSUE TITLE
Comma for server names disallows alternate ports for tcp/ip

### ISSUE THREAD

**Issue by Kenvf** [crimdon/SQLToolkit#32]
Within the Run Single SQL Script a comma is interpreted as another server, but the comma is necessary when adding an alternate port to the server name.  Could this be changed to a semi colon?

**Comment by crimdon** [comment]
I'll have a look at it this week

**Comment by crimdon** [comment]
I've uploaded a new release. You can now specify the port number by servername:port

**Comment by Kenvf** [comment]
Thank you, kindly.
