### ISSUE TITLE
Enchanement request to allow SQL to be executed using table of contents file

### ISSUE THREAD

**Issue by greadtm** [crimdon/SQLToolkit#35]
Today the SQL files task executes in order by alphanumeric sort. We have had some DEV teams complain they don't want to rename all of their SQL files in a TFS branch to execute using the SQLToolKit. Would it be possible to add the ability for the SQL to get executed in order based on a table of contents text file as an option? DEV can add their files to the text file and the SQL would get executed in order based on the text file.

**Comment by crimdon** [comment]
I've added this to the latest version. Let me know if its what you required.

**Comment by crimdon** [comment]
Hi there,

Had to release a new version and remove the functionality that allows you to browse for the TOC file. You now just need to enter the file name and it has to be in the same folder as the scripts.

**Comment by ricardocovo** [comment]
Hello,

This update broke all of our existing tasks. After some debugging the issue for us is that "$executionOrder" is never empty. It has the executing path on it, so it was trying to look for a ToC file even if there was none.

Can you please check on this?

**Comment by crimdon** [comment]
Yes I noted that today after other people commented. I've replaced the field with a simple string for the time being so its fixed in the latest version.

**Comment by ricardocovo** [comment]
Thanks for the quick reply. Is the new version already published?

**Comment by crimdon** [comment]
Yes it is. Will release another one tomorrow when I've tested switching back to a filePath variable for $executionOrder. I've found a fix for it at least.

**Comment by ricardocovo** [comment]
Thanks!
