### ISSUE TITLE
Getting access denied executing RunSQLScripts (version 2.6.8)

### ISSUE THREAD

**Issue by greadtm** [crimdon/SQLToolkit#36]
We are getting the access denied on vsts agent running the task with the optional "File containing list of files to execute (optional)".  This is the using the latest version just published.

**Comment by crimdon** [comment]
Try upgrading to 2.6.9.
 I was forced to revert back to just entering the file as passing an empty filePath variable didn't work and trying to compare it to an environment variable didn't work for everyones setup

**Comment by greadtm** [comment]
Thanks for the fix. So Far we can run with/without optional file. Just some feedback for the future.... If new major functionality is introduced, you can always bump the major rev (rev3, etc..) of the task. This way the community could go back to rev2 in the case of a breaking change. TFS supports multiple revs of a task as long as the major version is bumped.
