### ISSUE TITLE
Ability to set WITH COMPRESSION

### ISSUE THREAD

**Issue by IanYates** [crimdon/SQLToolkit#38]
Using the query found here
https://stackoverflow.com/a/37068313/1053381

```
SELECT ISNULL((SELECT value FROM sys.configurations WHERE name = 'backup compression default'),-1)
```

you'll get one of three responses
0: backup compression is available but not on by default
1: backup compression is available and on by default
-1: backup compression is not available

Could we please add a tri-state setting to the backup command with these values?

`No compression`
It will explicitly add the command `WITH NO_COMPRESSION` to the backup statement

`Try compression`
It will check the server's compatibility with compression, and if found to be compatible, add the `WITH COMPRESSION` command.  Unfortunately SQL Server Express (all versions prior to 2016) doesn't support compression and actually errors if you ask it to do compression.

`Default compression`
Works as it does today - no explicit instruction in the backup command.  The server default will be used.  For those interested you can see the server defaults here: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/view-or-configure-the-backup-compression-default-server-configuration-option

For many deployments it's faster to enable backup compression.  I can set the server default, which is a nice stopgap, but it'd be nice to not have to manually set that up on the server if possible.

Thanks for the great tools!

**Comment by crimdon** [comment]
Yes I can add that. As it was Enterprise only before 2016, I'd have to do some error checking or maybe just leave it up to the user to set the correct option.

**Comment by IanYates** [comment]
Thanks.

It worked in standard edition too by the way :)

Hopefully you can avoid the error checking by using that query I suggested at the start of my post.  Effectively, asking if the `sys.configurations` table contains an entry for 'backup compression default'.  If it does then compression is supported.  For SQL Express 2014 and below, this doesn't exist.  (I have no experience with the "web" edition).

`SELECT value FROM sys.configurations WHERE name = 'backup compression default'`

It's important to still have an option to not append any option, and to be able to say "try compression" but have the tool silently fall back to not using compression if it's not supported.  

My goal...
I'd like to be able to update my 60+ environments using the one set of tasks, where the task tries to use backup compression by default but doesn't crash on me if some of those environments are using SQL Express (as about half of them are).

Thank you :)

**Comment by crimdon** [comment]
I've released a new version and uploaded it. It also checks sys.configurations to see if the backup compression default exists before trying to compress.
#39

**Comment by IanYates** [comment]
I've just read through the PR - looks pretty straightforward.  Thanks so much.  I'll be trying it in the next day or so when I make a new release.  Cheers 🥂
