### ISSUE TITLE
SQL Functions created with vsts agent account

### ISSUE THREAD

**Issue by greadtm** [crimdon/SQLToolkit#42]
We use the 'Run SQL Scripts" deployment task. We have some SQL that drops and creates some functions within the SQL script. The function gets created with vsts agent account.function vs. dbo.function. When the function is referenced later in the SQL script as dbo.funciton, it cannot be located and the SQL deploy fails. Have you seen this in the past? We try executing this SQL inside management studio and it gets created with dbo.function.

**Comment by crimdon** [comment]
Not seen that before. Have you tried watching what is happening with profiler when the build task is running? I would check to see if any SQL exceptions are happening during the deployment.

**Comment by matthewmoon** [comment]
The account that VSTS is using, how is the security set up in SQL Server?  It should have a default schema and it probably is not set to dbo.

Alternatively, does the object in the Sql Database project have the dbo prefix for the name?  This would force the schema regardless of the users default schema.  I find this to be the better practice.

**Comment by crimdon** [comment]
Is this still an issue?
