### ISSUE TITLE
"Run Sql Scripts" gives "Incorrect syntax near 'GO'."

### ISSUE THREAD

**Issue by CodantiM** [crimdon/SQLToolkit#43]
With the "Run Sql Scripts" and "Run Single SQL Script" tasks if we have code to check for existence of a SP and drop it before creating it, we get an error: ##[error]Exception calling "ExecuteNonQuery" with "0" argument(s): "Incorrect syntax near 'GO'. 'CREATE/ALTER PROCEDURE' must be the first statement in a query batch." But the script has a GO between those sections so the script runs just fine in SSMS. (And in the "Run SQL Command" task if we take the final GO out.) I'm assuming that this is some issue with the parsing you are doing to the scripts?

See attached sample:
[usp_Test.zip](https://github.com/crimdon/SQLToolkit/files/1428215/usp_Test.zip)

I think the problem is caused by whitespace before the GO command, which SSMS allows.

So I think the regex just needs to have a "\s*" added to it. For maybe example '\r?\ngo' should be '\r?\n\s*go'?

**Comment by crimdon** [comment]
Yes I agree this is due to the white space. I'll add the \s* and retest

**Comment by crimdon** [comment]
I've updated the task and uploaded a new version. It all appears work now
