### ISSUE TITLE
Task fails on script with GOTO

### ISSUE THREAD

**Issue by displaced** [crimdon/SQLToolkit#47]
Hi,

We have many Run SQL Command tasks which create SQL Agent jobs.  These scripts were generated from the same template used by SQL Server Management Studio when right-clicking a job and choosing 'script job as CREATE'.

These Run SQL tasks have been failing as of today with an 'Incorrect syntax near TRANSACTION' error.

We traced it to the line:

`GOTO EndSave`

The query works if we change that line so that GOTO is not at the start of the line, e.g.:

`/* */ GOTO EndSave`

**Comment by crimdon** [comment]
Yeah I can see how that will happen. I'll have to adjust the regex so that it ignores GOTO and only find GO. Will get back to you when I have a fix out

**Comment by crimdon** [comment]
Fix uploaded

**Comment by displaced** [comment]
Hi,

Apologies for re-opening, but it looks like the RunSqlCommand task hasn't been updated with the new RegEx.    Others, like RunSingleSqlScript seem fine though.

Thanks,
Chris

**Comment by crimdon** [comment]
Sorry about that. Typo something back to front.

Updated now
