### ISSUE TITLE
Query timeout not working for SqlBackup

### ISSUE THREAD

**Issue by jmichaud-ips** [crimdon/SQLToolkit#5]
Based on looking at the current code, $querytimeout is never set.  [string]$userPassword = Get-VstsInput -Name queryTimeout.

Insetad the userPassword gets set with the value from queryTimeout parameter.

**Comment by jmichaud-ips** [comment]
I should clarify, this is for the SqlBackup script, the others look correct.  Editing title of issue.

**Comment by crimdon** [comment]
Thanks for that. I've fixed it and released a patch
