### ISSUE TITLE
SQL Server Tools installed on D:

### ISSUE THREAD

**Issue by GrumpyBusted** [crimdon/SQLToolkit#54]
Hi, SQL Server Tools are in installed on D:\Program Files... on our build server. would it be possible to give the location of the SQL Server Tools as Advanced arguments?

**Comment by crimdon** [comment]
Are you taking about the path to the DACPAC binaries?

**Comment by GrumpyBusted** [comment]
No, to the sql tools. Sqlpackage.exe and the Dlls that you are using. Nice plugin by the way :-)

**Comment by crimdon** [comment]
I've added the field but not had a chance to give it a good test. Please try it out and see if it works for you.

**Comment by GrumpyBusted** [comment]
Thanks, I will test within the next week

**Comment by GrumpyBusted** [comment]
Hi, again, it looks like it works like a charm, thanks for the help. But I get another unrelated error.
Exception calling "Deploy" with "5" argument(s): "Could not deploy package."
I have found a few comments on stackoverflow on this, and some says old defect in DAC Tools and other was firewall. I can deploy from my machine to database with SqlPackage.exe but not "Microsoft.SqlServer.Dac.dll". I am not sure want this is. I am sure it is not a problem with your extension, but if you have knowledge about this error, please help.

**Comment by crimdon** [comment]
Sorry I don't have much experience with DACPACS. In fact this task was written by somebody else and I've just maintained it.
