### ISSUE TITLE
Run scripts with a comment directly after a GO statement

### ISSUE THREAD

**Issue by harrywaters-swordmobile** [crimdon/SQLToolkit#57]
I have noticed that an error is thrown when there is a comment tag directly after a GO statement, e.g 

GO--BATCH

Will return the error:

incorrect syntax near 'GO'

**Comment by harrywaters-swordmobile** [comment]
Upon further testing it happens with any comment on the same line as a GO statement

**Comment by crimdon** [comment]
I'll have a look at this. Been a continuous problem as SQL is so flexible when adding comments.
