### ISSUE TITLE
No database-level error message

### ISSUE THREAD

**Issue by sevaa** [crimdon/SQLToolkit#6]
When a script errors out in the database, there's no diagnostic message as to what exactly went wrong.

To reproduce: create a database. Create a table in it:

`create table dbo.t(n int not null)`

Create a release definition with a "Run SQL Command" task in it, with the following SQL:

`insert into dbo.t(n) values(null)`

Execute the definition. See the log. No message about constraint violation, just a generic "Error running SQL script" message.

Some food for thought: http://stackoverflow.com/questions/27949081/how-do-you-get-powershell-script-output-in-the-deployment-log-for-a-vnext-releas

To fix: my testing shows that $_ object in the exception handler contains the raw error message as a string. So replace the exception handler in all the scripts with

`Write-Error "Error running SQL script: $_"`

and that will do the trick.

**Comment by crimdon** [comment]
I've added that. Also added a switch to the Invoke-SQLcmd to output sql errors

**Comment by sevaa** [comment]
The sensible message is there.

There's still a wrinkle - when the error is in a stored procedure, the error message doesn't reflect the SP name and the line number in the SP. SQL Server's error diagnostics do provide that, and most query tools output it, but invoke-sqlcmd doesn't. That's Microsoft's issue which [I've promptly reported to them](https://connect.microsoft.com/SQLServer/Feedback/Details/3101172). If you're as unhappy about it as I am, please click on the link, and once there, click on "Me too".
