### ISSUE TITLE
Systematic Error during ExecuteSQL Script Task

### ISSUE THREAD

**Issue by mbellengier** [crimdon/SQLToolkit#62]
I have an error during ExecuteSQL Script Task since the last update 2.8.0

Starting: Mise à jour BDD TIS_V5_CONFIGURATION
******************************************************************************
Processing Server  fs-sqlc1.fsavoir.lille\tisv5c
Processing database  TIS_V5_CONFIGURATION
Running all scripts in E:\Agent_build01\_work\9\s\Source\TourInSoft.V5\updateBDDConfig.sql
Running Script  updateBDDConfig.sql
Error running SQL script
Impossible de traiter la commande, car un ou plusieurs paramètres obligatoires sont absents : Process.
******************************************************************************
Finishing: Mise à jour BDD TIS_V5_CONFIGURATION

The updateBDDConfig.sql file has only one line of sql comment : 

-- DEPLOY Release-141

**Comment by crimdon** [comment]
This bug is caused when you check the Remove comments box
