### ISSUE TITLE
Query timeout field missing from TFS extension

### ISSUE THREAD

**Issue by jmichaud-ips** [crimdon/SQLToolkit#7]
Got your extension installed, 1.7.9, thank you for this extension! However, I noticed in the tfs release step that QueryTimeout in seconds exists in the advanced options with a label, but there isn't an input field to allow me to add seconds. 

![image](https://cloud.githubusercontent.com/assets/18216502/18176381/f2b7b4ae-703a-11e6-882f-3a6af938347e.png)

**Comment by crimdon** [comment]
I've fixed that issue and will release a new version today
